# Problem 1683: Invalid Tweets

## Description
Table: **Tweets**

| Column Name | Type    |
|-------------|---------|
| tweet_id    | int     |
| content     | varchar |

- `tweet_id` is the primary key for this table.
- The `content` column consists of characters from an American keyboard and contains no special characters.
- This table contains all tweets in a social media app.

The task is to find the IDs of tweets that are invalid. A tweet is considered invalid if the number of characters in the `content` column exceeds 15.

Return the result in any order.

## Examples

### Example 1

**Input:**  
**Tweets** table:

| tweet_id | content                           |
|----------|-----------------------------------|
| 1        | Let us Code                       |
| 2        | More than fifteen chars are here! |

**Output:**  

| tweet_id |
|----------|
| 2        |

**Explanation:**  
- Tweet 1 has a length of 11 characters and is valid.
- Tweet 2 has a length of 33 characters and is invalid.

## Constraints
- `tweet_id` is guaranteed to be unique.
- The length of the `content` column can vary but consists only of American keyboard characters.

## Follow Up
What would be the optimal query to identify invalid tweets if the table had millions of entries?

# Implementation

In [1]:
import random

In [2]:
import string

In [3]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [4]:
string.digits

'0123456789'

string.key

In [12]:
def get_keyboard_chars():
    keyboard_chars = []
    for i in range(32, 127):  
        keyboard_chars.append(chr(i))
    keyboard_chars.append(" ")
    return keyboard_chars

keyboard_chars = get_keyboard_chars()
print(keyboard_chars)

[' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', ' ']

In [15]:
tweet_id_list = list(range(50))

In [16]:
def get_n_tweets(n=50):
    return ["".join([random.choice(keyboard_chars) for _ in range(random.randint(1, 45))]) for _ in range(n)]

In [17]:
tweet_content_list = get_n_tweets()

In [18]:
tweet_content_list

["R<%UZ$'c/ $b6YD$8Hs!Ar_y=4}o?ewa,+@)2+d",
 'v $]-:+)k',
 'p"}<0Ix,8Hj\\O[`/92;t{hhMKROznrPY%?k~9d',
 'g_nNPSJ"=.,&7A<i=[&!f<$W$OQWcq4|i;lcIj',
 "H'&u\\OarsZm{zlP4}^QxF7kQIs](V@bpXkJ]",
 'Awj~tP',
 'hEO[nJ|(|]@',
 'amPJDvf*srY 8H',
 'A l8{5z1fS"0\\<?lz',
 'iY C(A',
 'T~f3^m_C!^shwSWf.~v tfBQYsg&NR.r~KG6',
 "!toh8{lAY{]v<'M' St=~\\}/Kb;-./``z/}C9uB",
 'r6MHSJZ."ALs}yi4rqYyJ`3sC"Br-asP+q%HJ,_zpjlD"',
 'q=!^.18q F/M`rBw;tHVW( BGyMmvZ',
 'UH25KxAjB-Y4V>)ed!apmE:Bx+;.Mg_6oF[S',
 "\\?Eis-7h.;6#t#;Pfp.'?XEBD,QLV{R^',.B?5.hz BD",
 'H G^8]3lKQ =|!sGTo{e273aym3SS?FSw8qg#adl6?+',
 "`zP'^}'/e'mB",
 '@<*c+EOy3Rt{%p@>GHhf8:!~wFa] 0G,>\\sK{ b',
 'Qz= .+jvhBeYA; T#:!-',
 'IFw(-v8K_&U`] )YNT#T4SzV%',
 '@ NmOr>h)!4}m<`s2$9MsR. *H;PYm?R1$]m/i.3',
 ' QmInI%C.d5M-XL @3}NoQ%#pFj<',
 '^D7G}xolO"DTQE>YB',
 'Fhv* H48Q#LY0F1Qq1UxQy:Iv*f~HymUK=te[4I;6yw',
 '|/"b.3sg0"SaKW8C\\0sy.B+^XP',
 "``)1P}cEOU^@;QX|3c/_)_wwQ)V'gXXe4u",
 'KON7`b&r(vJ^fW5DBa Quo43`z!wDy]myU',
 'T)l\'~^G`3kn"NX_|\\/%[Ng|Wi):~T<Lw]} npDH}a',
 ';|c$Lq]Uaal,>G4QS2z!N83;QzyM9Q',
 '!.3:Kn#qFNlGGM[FY\\3|k}!Y',
 ')Wj"rBUOH|]Y8s1',
 'wiB.[#+]`p7N:X',
 'V7Tu[I%l!O`svB/wem"]HPBVnnh}30"[3dC/0-~;rD',
 '2g(\\,sv^C6SFOke%=m&,ky&DF[4e?QSt',
 '0 ji~gSl50_9"Mbi<Y|WTf3h}L(072b&G0',
 'MI8cpx5,',
 '\\8!cADx**{KyuqRR',
 'mf`giI*$dBsn%h%E$WJIE-/;5rWda/`IV7',
 'Ws|J#qd75*Ztb ~,BObCWma2Z5h@H7eAsrd}C',
 'O,<wt_|:dZRXm\\}n',
 ':&QxsW*~cj`*)s%%d$A)]l`J,a4r>HA{faDis=-/7DY7',
 'k',
 '{uLL~I;9B}>c18.tn&>c(aLlAD1MjZOK,YNwdxP',
 'wy \\:zk@oYA};p% (eQ2SNKtBVH',
 "Jg;;71rN {3ur)Aavb~B['X",
 'wGCOnwrH+x1\\hjpU]h*W)c^lINc!O<.1N&niLj0&',
 'V,t%KP[(Q  7Y)FhX,:',
 "'S}r^ x`U}Y+{<nAq}5PVMeg=a!'W[JyU`>fNa--&='",
 '4w=Km7gr1 0a?{{c9BU6G\\DYU4PldlNu;"TFf']

In [19]:
import pandas as pd

In [24]:
df = pd.DataFrame(list(zip(tweet_id_list, tweet_content_list)), columns=['tweet_id', 'tweet_content'])

In [25]:
df.head()

   tweet_id                            tweet_content
0         0  R<%UZ$'c/ $b6YD$8Hs!Ar_y=4}o?ewa,+@)2+d
1         1                                v $]-:+)k
2         2   p"}<0Ix,8Hj\O[`/92;t{hhMKROznrPY%?k~9d
3         3   g_nNPSJ"=.,&7A<i=[&!f<$W$OQWcq4|i;lcIj
4         4     H'&u\OarsZm{zlP4}^QxF7kQIs](V@bpXkJ]

In [32]:
df.loc[df.loc[:, 'tweet_content'].str.len() <= 15, ['tweet_id']]

    tweet_id
1          1
5          5
6          6
7          7
9          9
17        17
31        31
32        32
36        36
42        42

In [ ]:
import pandas as pd

def invalid_tweets(tweets: pd.DataFrame) -> pd.DataFrame:

    return tweets.loc[tweets.loc[:, 'content'].str.len() > 15, ['tweet_id']]